version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:stretch
    steps:
      - checkout
      - run:
          name: Build bam
          command: |
            apt-get update -y
            apt-get install libsdl2-dev libfreetype6-dev -y
            git clone https://github.com/matricks/bam.git ~/bam
            cd ~/bam/
            git reset --hard f012dd9a3e38295b8a45af5a101d29573381f169
            ./make_unix.sh
      - run:
          name: Build teeworlds
          command: ~/bam/bam conf=release all