name: Build

on: [push, pull_request]

jobs:
  build-bam:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        include:
        - name: "Ubuntu-Latest x86_64"
          os: ubuntu-latest
          package-full-file: ninslash-linux_x86_64-release.tar.xz

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Checkout bam
      uses: actions/checkout@v4
      with:
        repository: matricks/bam
        ref: 8cd08744c37666830d439ab54016c9d228c63b68
        path: ./bam

    - name: Prepare Linux
      if: contains(matrix.os, 'ubuntu')
      run: |
        sudo apt-get update -y
        sudo apt-get install bam libsdl2-dev python3 libglew-dev -y

    - name: Build in debug mode
      run: bam conf=debug

    - name: Build in release mode
      run: bam conf=release

    - name: Package Release
      if: contains(matrix.os, 'ubuntu')
      run: |
        mv build/x86_64/release/ninslash_srv build/x86_64/release/ninslash .
        tar -cf ${{ matrix.package-full-file }} ninslash_srv ninslash data/ cfg/ storage.cfg license.txt autoexec.cfg
        
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.name }}
        path: ${{ matrix.package-full-file }}