name: Build

on: [push, pull_request]

jobs:
  build-bam:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Checkout bam
      uses: actions/checkout@v2
      with:
        repository: matricks/bam
        ref: 8cd08744c37666830d439ab54016c9d228c63b68
        path: ./bam

    - name: Prepare Linux
      if: contains(matrix.os, 'ubuntu')
      run: |
        sudo apt-get update -y
        sudo apt-get install libfreetype6-dev libsdl2-dev -y
        cd bam
        ./make_unix.sh
    - name: Prepare MacOS
      if: contains(matrix.os, 'macOS')
      run: |
        brew update
        brew install sdl2
        cd bam
        ./make_unix.sh
    - name: Prepare Windows
      if: contains(matrix.os, 'windows')
      run: |
        cd bam
        ./make_win64_msvc.bat
    - name: Build in debug mode
      run: ./bam/bam conf=debug all
    - name: Test debug
      run: ./build/x86_64/debug/ninslash_srv shutdown

    - name: Build in release mode
      run: ./bam/bam conf=release all
    - name: Test release
      run: ./build/x86_64/release/ninslash_srv shutdown

    - name: Create MacOS app using make_release.py
      if: contains(matrix.os, 'macOS')
      run: |
        sudo python3 scripts/make_release.py master osx
